# Change these first
owner: upptime # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Flott
    url: https://goflott.com
  - name: Flott Web App
    url: https://app.goflott.com
  - name: Flott API
    url: https://api.goflott.com/dispatch/v1/company/
    headers:
      - "Authorization: $FLOTT_API_KEY"

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.goflott.com
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Flott Status
  introTitle: "**Flott** Transforming Transportation in Südtirol."
  introMessage: By connecting passengers with reliable drivers and optimizing routes, we're making transportation more efficient, accessible, and environmentally friendly for everyone.
  navbar:
    - title: Status
      href: /
    - title: Flott
      href: https://goflott.com

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
